name: Create archives

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create archives
      run: |
        mkdir -p releases
        for i in *
        do
            if [ -d "$i" ] && [ ! "$i" == "releases" ]
            then
                zip -r "releases/$i.zip" "$i"
                tar -zcvf "releases/$i.tar.gz" "$i"
            fi
        done
      shell: bash
    - name: Upload Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: releases/*
        file_glob: true
        tag: downloads
        overwrite: true
